_target_: src.datamodules.data_new.GraphDataModule
data_dir: ${paths.data_dir}/dailyroot
#data_dir: ${oc.env:PROJECT_ROOT}/dailyroot
batch_size: 5
train_val_test_split: [0.80,0.10,0.10]
num_workers: 4 # os.cpu_count()
pin_memory: False

